#!/bin/bash

# Autor: César Voginski <cesarvog@cesarvog.dev>
# Manage bookmarks
#TODO evict duplicates in file

openLink() {
	if [[ "$1" =~ ^gopher* ]]; then
		alacritty -e lynx $1 
	else
		$BROWSER $1 &
	fi
}

if [ -n "$1" ]; then
	echo $@ >> ~/webmarks.txt	
	exit
fi

choose=$(cat ~/webmarks.txt | dmenu | awk '{print $1}')
[ "$?" = "0" ] && [ -n "$choose" ] && openLink $choose 

