#!/bin/bash

# Autor: César Voginski <cesarvog@cesarvog.dev>
# Manage bookmarks
#TODO evict duplicates in file

file=~/.data/webmarks

openLink() {
	if [[ "$1" =~ ^gopher* ]]; then
		alacritty -e lynx $1 
	else
		brave $1 &
	fi
}

if [ -n "$1" ]; then
	echo $@ >> $file
	exit
fi

choose=$(cat $file | dmenu | awk '{print $1}')
[ "$?" = "0" ] && [ -n "$choose" ] && openLink $choose 

